#!/bin/bash
echo "========================="
echo "   SYSTEM INFORMATION    "
echo "========================="
echo "Hostname: $(hostname)"
echo "OS: $(uname -o)"
echo "Kernel: $(uname -r)"
echo "Uptime: $(uptime -p)"
echo "CPU Cores: $(nproc)"
echo "RAM Total: $(free -h  | awk '/Mem/{print $2}')"
echo "RAM Used: $(free -h   | awk '/Mem/{print $3}')"
echo "Disk Total: $(df -h / | awk 'NR==2{print $2}')"
echo "Disk Used : $(df -h / | awk 'NR==2{print $3}')"
echo "========================="
